
namespace SyncronizationBot.Domain.Model.CrossCutting.Birdeye.TokenOverview.Response
{
    public class TokenOverviewResponse
    {
        public ResultData? Data { get; set; }
        public bool Success { get; set; }

    }
    public class ResultData
    {
        public string? Address { get; set; }
        public decimal? Decimals { get; set; }
        public string? Symbol { get; set; }
        public string? Name { get; set; }
        public ResultExtensions? Extensions { get; set; }
        public Uri? LogoUri { get; set; }
        public decimal? Liquidity { get; set; }
        public decimal? Price { get; set; }
        public decimal? History30MPrice { get; set; }
        public decimal? PriceChange30MPercent { get; set; }
        public decimal? History1HPrice { get; set; }
        public decimal? PriceChange1HPercent { get; set; }
        public decimal? History2HPrice { get; set; }
        public decimal? PriceChange2HPercent { get; set; }
        public decimal? History4HPrice { get; set; }
        public decimal? PriceChange4HPercent { get; set; }
        public decimal? History6HPrice { get; set; }
        public decimal? PriceChange6HPercent { get; set; }
        public decimal? History8HPrice { get; set; }
        public decimal? PriceChange8HPercent { get; set; }
        public decimal? History12HPrice { get; set; }
        public decimal? PriceChange12HPercent { get; set; }
        public decimal? History24HPrice { get; set; }
        public decimal? PriceChange24HPercent { get; set; }
        public decimal? UniqueWallet30M { get; set; }
        public decimal? UniqueWalletHistory30M { get; set; }
        public decimal? UniqueWallet30MChangePercent { get; set; }
        public decimal? UniqueWallet1H { get; set; }
        public decimal? UniqueWalletHistory1H { get; set; }
        public decimal? UniqueWallet1HChangePercent { get; set; }
        public decimal? UniqueWallet2H { get; set; }
        public decimal? UniqueWalletHistory2H { get; set; }
        public decimal? UniqueWallet2HChangePercent { get; set; }
        public decimal? UniqueWallet4H { get; set; }
        public decimal? UniqueWalletHistory4H { get; set; }
        public decimal? UniqueWallet4HChangePercent { get; set; }
        public decimal? UniqueWallet6H { get; set; }
        public decimal? UniqueWalletHistory6H { get; set; }
        public decimal? UniqueWallet6HChangePercent { get; set; }
        public decimal? UniqueWallet8H { get; set; }
        public decimal? UniqueWalletHistory8H { get; set; }
        public decimal? UniqueWallet8HChangePercent { get; set; }
        public decimal? UniqueWallet12H { get; set; }
        public decimal? UniqueWalletHistory12H { get; set; }
        public decimal? UniqueWallet12HChangePercent { get; set; }
        public decimal? UniqueWallet24H { get; set; }
        public decimal? UniqueWalletHistory24H { get; set; }
        public decimal? UniqueWallet24HChangePercent { get; set; }
        public decimal? LastTradeUnixTime { get; set; }
        public DateTimeOffset? LastTradeHumanTime { get; set; }
        public decimal? Supply { get; set; }
        public decimal? Mc { get; set; }
        public decimal? Trade30M { get; set; }
        public decimal? TradeHistory30M { get; set; }
        public decimal? Trade30MChangePercent { get; set; }
        public decimal? Sell30M { get; set; }
        public decimal? SellHistory30M { get; set; }
        public decimal? Sell30MChangePercent { get; set; }
        public decimal? Buy30M { get; set; }
        public decimal? BuyHistory30M { get; set; }
        public decimal? Buy30MChangePercent { get; set; }
        public decimal? V30M { get; set; }
        public decimal? V30MUsd { get; set; }
        public decimal? VHistory30M { get; set; }
        public decimal? VHistory30MUsd { get; set; }
        public decimal? V30MChangePercent { get; set; }
        public decimal? VBuy30M { get; set; }
        public decimal? VBuy30MUsd { get; set; }
        public decimal? VBuyHistory30M { get; set; }
        public decimal? VBuyHistory30MUsd { get; set; }
        public decimal? VBuy30MChangePercent { get; set; }
        public decimal? VSell30M { get; set; }
        public decimal? VSell30MUsd { get; set; }
        public decimal? VSellHistory30M { get; set; }
        public decimal? VSellHistory30MUsd { get; set; }
        public decimal? VSell30MChangePercent { get; set; }
        public decimal? Trade1H { get; set; }
        public decimal? TradeHistory1H { get; set; }
        public decimal? Trade1HChangePercent { get; set; }
        public decimal? Sell1H { get; set; }
        public decimal? SellHistory1H { get; set; }
        public decimal? Sell1HChangePercent { get; set; }
        public decimal? Buy1H { get; set; }
        public decimal? BuyHistory1H { get; set; }
        public decimal? Buy1HChangePercent { get; set; }
        public decimal? V1H { get; set; }
        public decimal? V1HUsd { get; set; }
        public decimal? VHistory1H { get; set; }
        public decimal? VHistory1HUsd { get; set; }
        public decimal? V1HChangePercent { get; set; }
        public decimal? VBuy1H { get; set; }
        public decimal? VBuy1HUsd { get; set; }
        public decimal? VBuyHistory1H { get; set; }
        public decimal? VBuyHistory1HUsd { get; set; }
        public decimal? VBuy1HChangePercent { get; set; }
        public decimal? VSell1H { get; set; }
        public decimal? VSell1HUsd { get; set; }
        public decimal? VSellHistory1H { get; set; }
        public decimal? VSellHistory1HUsd { get; set; }
        public decimal? VSell1HChangePercent { get; set; }
        public decimal? Trade2H { get; set; }
        public decimal? TradeHistory2H { get; set; }
        public decimal? Trade2HChangePercent { get; set; }
        public decimal? Sell2H { get; set; }
        public decimal? SellHistory2H { get; set; }
        public decimal? Sell2HChangePercent { get; set; }
        public decimal? Buy2H { get; set; }
        public decimal? BuyHistory2H { get; set; }
        public decimal? Buy2HChangePercent { get; set; }
        public decimal? V2H { get; set; }
        public decimal? V2HUsd { get; set; }
        public decimal? VHistory2H { get; set; }
        public decimal? VHistory2HUsd { get; set; }
        public decimal? V2HChangePercent { get; set; }
        public decimal? VBuy2H { get; set; }
        public decimal? VBuy2HUsd { get; set; }
        public decimal? VBuyHistory2H { get; set; }
        public decimal? VBuyHistory2HUsd { get; set; }
        public decimal? VBuy2HChangePercent { get; set; }
        public decimal? VSell2H { get; set; }
        public decimal? VSell2HUsd { get; set; }
        public decimal? VSellHistory2H { get; set; }
        public decimal? VSellHistory2HUsd { get; set; }
        public decimal? VSell2HChangePercent { get; set; }
        public decimal? Trade4H { get; set; }
        public decimal? TradeHistory4H { get; set; }
        public decimal? Trade4HChangePercent { get; set; }
        public decimal? Sell4H { get; set; }
        public decimal? SellHistory4H { get; set; }
        public decimal? Sell4HChangePercent { get; set; }
        public decimal? Buy4H { get; set; }
        public decimal? BuyHistory4H { get; set; }
        public decimal? Buy4HChangePercent { get; set; }
        public decimal? V4H { get; set; }
        public decimal? V4HUsd { get; set; }
        public decimal? VHistory4H { get; set; }
        public decimal? VHistory4HUsd { get; set; }
        public decimal? V4HChangePercent { get; set; }
        public decimal? VBuy4H { get; set; }
        public decimal? VBuy4HUsd { get; set; }
        public decimal? VBuyHistory4H { get; set; }
        public decimal? VBuyHistory4HUsd { get; set; }
        public decimal? VBuy4HChangePercent { get; set; }
        public decimal? VSell4H { get; set; }
        public decimal? VSell4HUsd { get; set; }
        public decimal? VSellHistory4H { get; set; }
        public decimal? VSellHistory4HUsd { get; set; }
        public decimal? VSell4HChangePercent { get; set; }
        public decimal? Trade6H { get; set; }
        public decimal? TradeHistory6H { get; set; }
        public decimal? Trade6HChangePercent { get; set; }
        public decimal? Sell6H { get; set; }
        public decimal? SellHistory6H { get; set; }
        public decimal? Sell6HChangePercent { get; set; }
        public decimal? Buy6H { get; set; }
        public decimal? BuyHistory6H { get; set; }
        public decimal? Buy6HChangePercent { get; set; }
        public decimal? V6H { get; set; }
        public decimal? V6HUsd { get; set; }
        public decimal? VHistory6H { get; set; }
        public decimal? VHistory6HUsd { get; set; }
        public decimal? V6HChangePercent { get; set; }
        public decimal? VBuy6H { get; set; }
        public decimal? VBuy6HUsd { get; set; }
        public decimal? VBuyHistory6H { get; set; }
        public decimal? VBuyHistory6HUsd { get; set; }
        public decimal? VBuy6HChangePercent { get; set; }
        public decimal? VSell6H { get; set; }
        public decimal? VSell6HUsd { get; set; }
        public decimal? VSellHistory6H { get; set; }
        public decimal? VSellHistory6HUsd { get; set; }
        public decimal? VSell6HChangePercent { get; set; }
        public decimal? Trade8H { get; set; }
        public decimal? TradeHistory8H { get; set; }
        public decimal? Trade8HChangePercent { get; set; }
        public decimal? Sell8H { get; set; }
        public decimal? SellHistory8H { get; set; }
        public decimal? Sell8HChangePercent { get; set; }
        public decimal? Buy8H { get; set; }
        public decimal? BuyHistory8H { get; set; }
        public decimal? Buy8HChangePercent { get; set; }
        public decimal? V8H { get; set; }
        public decimal? V8HUsd { get; set; }
        public decimal? VHistory8H { get; set; }
        public decimal? VHistory8HUsd { get; set; }
        public decimal? V8HChangePercent { get; set; }
        public decimal? VBuy8H { get; set; }
        public decimal? VBuy8HUsd { get; set; }
        public decimal? VBuyHistory8H { get; set; }
        public decimal? VBuyHistory8HUsd { get; set; }
        public decimal? VBuy8HChangePercent { get; set; }
        public decimal? VSell8H { get; set; }
        public decimal? VSell8HUsd { get; set; }
        public decimal? VSellHistory8H { get; set; }
        public decimal? VSellHistory8HUsd { get; set; }
        public decimal? VSell8HChangePercent { get; set; }
        public decimal? Trade12H { get; set; }
        public decimal? TradeHistory12H { get; set; }
        public decimal? Trade12HChangePercent { get; set; }
        public decimal? Sell12H { get; set; }
        public decimal? SellHistory12H { get; set; }
        public decimal? Sell12HChangePercent { get; set; }
        public decimal? Buy12H { get; set; }
        public decimal? BuyHistory12H { get; set; }
        public decimal? Buy12HChangePercent { get; set; }
        public decimal? V12H { get; set; }
        public decimal? V12HUsd { get; set; }
        public decimal? VHistory12H { get; set; }
        public decimal? VHistory12HUsd { get; set; }
        public decimal? V12HChangePercent { get; set; }
        public decimal? VBuy12H { get; set; }
        public decimal? VBuy12HUsd { get; set; }
        public decimal? VBuyHistory12H { get; set; }
        public decimal? VBuyHistory12HUsd { get; set; }
        public decimal? VBuy12HChangePercent { get; set; }
        public decimal? VSell12H { get; set; }
        public decimal? VSell12HUsd { get; set; }
        public decimal? VSellHistory12H { get; set; }
        public decimal? VSellHistory12HUsd { get; set; }
        public decimal? VSell12HChangePercent { get; set; }
        public decimal? Trade24H { get; set; }
        public decimal? TradeHistory24H { get; set; }
        public decimal? Trade24HChangePercent { get; set; }
        public decimal? Sell24H { get; set; }
        public decimal? SellHistory24H { get; set; }
        public decimal? Sell24HChangePercent { get; set; }
        public decimal? Buy24H { get; set; }
        public decimal? BuyHistory24H { get; set; }
        public decimal? Buy24HChangePercent { get; set; }
        public decimal? V24H { get; set; }
        public decimal? V24HUsd { get; set; }
        public decimal? VHistory24H { get; set; }
        public decimal? VHistory24HUsd { get; set; }
        public decimal? V24HChangePercent { get; set; }
        public decimal? VBuy24H { get; set; }
        public decimal? VBuy24HUsd { get; set; }
        public decimal? VBuyHistory24H { get; set; }
        public decimal? VBuyHistory24HUsd { get; set; }
        public decimal? VBuy24HChangePercent { get; set; }
        public decimal? VSell24H { get; set; }
        public decimal? VSell24HUsd { get; set; }
        public decimal? VSellHistory24H { get; set; }
        public decimal? VSellHistory24HUsd { get; set; }
        public decimal? VSell24HChangePercent { get; set; }
        public decimal? Watch { get; set; }
        public decimal? View30M { get; set; }
        public decimal? ViewHistory30M { get; set; }
        public decimal? View30MChangePercent { get; set; }
        public decimal? View1H { get; set; }
        public decimal? ViewHistory1H { get; set; }
        public decimal? View1HChangePercent { get; set; }
        public decimal? View2H { get; set; }
        public decimal? ViewHistory2H { get; set; }
        public decimal? View2HChangePercent { get; set; }
        public decimal? View4H { get; set; }
        public decimal? ViewHistory4H { get; set; }
        public decimal? View4HChangePercent { get; set; }
        public decimal? View6H { get; set; }
        public decimal? ViewHistory6H { get; set; }
        public decimal? View6HChangePercent { get; set; }
        public decimal? View8H { get; set; }
        public decimal? ViewHistory8H { get; set; }
        public decimal? View8HChangePercent { get; set; }
        public decimal? View12H { get; set; }
        public decimal? ViewHistory12H { get; set; }
        public decimal? View12HChangePercent { get; set; }
        public decimal? View24H { get; set; }
        public decimal? ViewHistory24H { get; set; }
        public decimal? View24HChangePercent { get; set; }
        public decimal? UniqueView30M { get; set; }
        public decimal? UniqueViewHistory30M { get; set; }
        public decimal? UniqueView30MChangePercent { get; set; }
        public decimal? UniqueView1H { get; set; }
        public decimal? UniqueViewHistory1H { get; set; }
        public decimal? UniqueView1HChangePercent { get; set; }
        public decimal? UniqueView2H { get; set; }
        public decimal? UniqueViewHistory2H { get; set; }
        public decimal? UniqueView2HChangePercent { get; set; }
        public decimal? UniqueView4H { get; set; }
        public decimal? UniqueViewHistory4H { get; set; }
        public decimal? UniqueView4HChangePercent { get; set; }
        public decimal? UniqueView6H { get; set; }
        public decimal? UniqueViewHistory6H { get; set; }
        public decimal? UniqueView6HChangePercent { get; set; }
        public decimal? UniqueView8H { get; set; }
        public decimal? UniqueViewHistory8H { get; set; }
        public decimal? UniqueView8HChangePercent { get; set; }
        public decimal? UniqueView12H { get; set; }
        public decimal? UniqueViewHistory12H { get; set; }
        public decimal? UniqueView12HChangePercent { get; set; }
        public decimal? UniqueView24H { get; set; }
        public decimal? UniqueViewHistory24H { get; set; }
        public decimal? UniqueView24HChangePercent { get; set; }
        public decimal? NumberMarkets { get; set; }
    }

    public class ResultExtensions
    {
        public string? CoingeckoId { get; set; }
        public string? Description { get; set; }
        public string? Telegram { get; set; }
        public string? Twitter { get; set; }
        public string? Website { get; set; }
    }
}
