USE [master]
GO

/****** Object:  Database [Monitoring]    Script Date: 04/01/2024 19:01:08 ******/
CREATE DATABASE [Monitoring]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Monitoring', FILENAME = N'/var/opt/mssql/data/Monitoring.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Monitoring_log', FILENAME = N'/var/opt/mssql/data/Monitoring_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Monitoring].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Monitoring] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Monitoring] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Monitoring] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Monitoring] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Monitoring] SET ARITHABORT OFF 
GO

ALTER DATABASE [Monitoring] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Monitoring] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Monitoring] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Monitoring] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Monitoring] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Monitoring] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Monitoring] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Monitoring] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Monitoring] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Monitoring] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Monitoring] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Monitoring] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Monitoring] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Monitoring] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Monitoring] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Monitoring] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Monitoring] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Monitoring] SET RECOVERY FULL 
GO

ALTER DATABASE [Monitoring] SET  MULTI_USER 
GO

ALTER DATABASE [Monitoring] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Monitoring] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Monitoring] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Monitoring] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Monitoring] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Monitoring] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Monitoring] SET  READ_WRITE 
GO


