version: "3.9"
name: monitoring-services
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge   

#docker run --name sql-server -e "ACCEPT_EULA=Y" -e "MSSQL_PID=Enterprise" -e "MSSQL_AGENT_ENABLED=True" -e "MSSQL_SA_PASSWORD=M@ni@co2024" -p 1402:1433 -d mcr.microsoft.com/mssql/server:2022-latest
#docker run --name mongodb -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=M@ni@co2024 -d mongo:latest